{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bb-serial.fullname" . }}
  labels:
    {{- include "bb-serial.labels" . | nindent 4 }}
  annotations:
    # Prevent Helm from diffing secret values in plain text
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  DISCORD_TOKEN: {{ .Values.secrets.discordToken | quote }}
  DISCORD_CLIENT_SECRET: {{ .Values.secrets.discordClientSecret | quote }}
  WEB_SECRET_KEY: {{ .Values.secrets.webSecretKey | quote }}
{{- end }}
